swagger: '2.0'
info:
  description: The API for my.move.mil
  version: 0.0.1
  title: my.move.mil
  contact:
    email: ppp@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

basePath: /api/v1

paths:
  /issues:
    post:
      summary: Create a new issue
      description: Issues represent problems or suggestions for the app, this creates a new one.
      operationId: createIssue
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: issue
        schema:
          type: object
          required:
          - body
          properties:
            body:
              type: string
              example: This is a test issue
      responses:
        201:
          description: created issue
          schema:
            $ref: '#/definitions/Issue'
        400:
          description: invalid request
    get:
      summary: List all issues
      description: List all issues
      operationId: indexIssues
      produces:
      - application/json
      responses:
        200:
          description: list of issues
          schema:
            type: array
            items:
              $ref: '#/definitions/Issue'
        400:
          description: invalid request
  /form1299:
    post:
      summary: Create a new shipment or storage of personal property application
      description: Create an instance of form 1299
      operationId: createForm1299
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: createForm1299Payload
        required: true
        schema:
          $ref: "#/definitions/CreateForm1299Payload"
      responses:
        201:
          description: created instance of form 1299
          schema:
            $ref: '#/definitions/Form1299Response'
        400:
          description: invalid request
    get:
      summary: List all submitted 1299 forms
      description: List all submitted 1299 forms
      operationId: indexForm1299s
      produces:
      - application/json
      responses:
        200:
          description: list of submitted form 1299s
          schema:
            type: array
            items:
              $ref: '#/definitions/IndexForm1299sResponse'
        400:
          description: invalid request

definitions:
  Issue:
    type: object
    required:
    - id
    - body
    - created_at
    - updated_at
    properties:
      id:
        type: string
        format: uuid
        example: 116a53150-f0e3-11e7-8c3f-9a214cf093ae
      body:
        type: string
        example: This is a test issue
      created_at:
        type: dateTime
      updated_at:
        type: dateTime
  CreateForm1299Payload:
    type: object
    required:
      - service_member_ssn
    properties:
      date_prepared:
        type: string
        format: date
        example: 2018-01-03
        nullable: true
      shipment_number:
        type: string
        example: 4550
        nullable: true
      name_of_preparing_office:
        type: string
        example: pumpernickel office
        nullable: true
      origin_office_address_name:
        type: string
        example: Office manager John Dough
        nullable: true
      origin_office_address_number:
        type: string
        example: '3450'
        nullable: true
      origin_office_address_street:
        type: string
        example: Kneading Way
        nullable: true
      origin_office_address_city:
        type: string
        example: San Francisco
        nullable: true
      origin_office_address_state:
        type: string
        example: California
        nullable: true
      origin_office_address_zip:
        type: string
        example: 94104
        nullable: true
      service_member_first_name:
        type: string
        example: Focaccia
        nullable: true
      service_member_middle_initial:
        example: L.
        nullable: true
        nullable: true
      service_member_last_name:
        type: string
        example: Roll
        nullable: true
      service_member_rank:
        type: string
        example: Commodore
        nullable: true
      service_member_ssn:
        type: string
        pattern: '^\d{3}-\d{2}-\d{4}$'
        example: 555-555-5555
      service_member_agency:
        type: string
        example: Air Force
        nullable: true
      hhg_total_pounds:
        type: number
        format: double
        example: 125.25
        nullable: true
      hhg_progear_pounds:
        type: number
        format: double
        example: 35.11
        nullable: true
      hhg_valuable_items_cartons:
        type: integer
        example: 3
        nullable: true
      mobile_home_serial_number:
        type: string
        example: 45kljs98kljlkwj5
        nullable: true
      mobile_home_length:
        type: number
        example: 72
        nullable: true
      mobile_home_width:
        type: number
        example: 15.4
        nullable: true
      mobile_home_height:
        type: number
        example: 10
        nullable: true
      mobile_home_type_expando:
        type: string
        example: bathroom and shower unit
        nullable: true
      mobile_home_services_requested:
        type: string
        enum:
        - contents packed
        - mobile home blocked
        - mobile home unblocked
        - stored at origin
        - stored at destination
        nullable: true
      station_orders_type:
        type: string
        enum:
        - permanent
        - temporary
        nullable: true
      station_orders_issued_by:
        type: string
        example: Sergeant Naan
        nullable: true
      station_orders_new_assignment:
        type: string
        example: ACCOUNTING OPS
        nullable: true
      station_orders_date:
        type: string
        format: date
        example: 2018-03-15
        nullable: true
      station_orders_number:
        type: string
        example: 98374
        nullable: true
      station_orders_paragraph_number:
        type: string
        example: 5
        nullable: true
      station_orders_in_transit_telephone:
        type: string
        pattern: '^[2-9]\d{2}-\d{3}-\d{4}$'
        example: 212-666-6666
        nullable: true
      in_transit_address_number:
        type: string
        nullable: true
      in_transit_address_street:
        type: string
        nullable: true
      in_transit_address_city:
        type: string
        nullable: true
      in_transit_address_state:
        type: string
        nullable: true
      in_transit_address_zip:
        type: string
        nullable: true
      pickup_address_number:
        type: string
        nullable: true
      pickup_address_street:
        type: string
        nullable: true
      pickup_address_city:
        type: string
        nullable: true
      pickup_address_county:
        type: string
        nullable: true
      pickup_address_state:
        type: string
        nullable: true
      pickup_address_zip:
        type: string
        nullable: true
      pickup_address_mobile_court_name:
        type: string
        example: Winnebagel court
        nullable: true
      pickup_telephone:
        type: string
        pattern: '^[2-9]\d{2}-\d{3}-\d{4}$'
        example: 212-555-5555
        nullable: true
      dest_address_number:
        type: string
        nullable: true
      dest_address_street:
        type: string
        nullable: true
      dest_address_city:
        type: string
        nullable: true
      dest_address_county:
        type: string
        nullable: true
      dest_address_state:
        type: string
        nullable: true
      dest_address_zip:
        type: string
        nullable: true
      dest_address_mobile_court_name:
        type: string
        example: Carraway Court
        nullable: true
      agent_to_receive_hhg:
        type: string
        nullable: true
      extra_address_number:
        type: string
        nullable: true
      extra_address_street:
        type: string
        nullable: true
      extra_address_city:
        type: string
        nullable: true
      extra_address_county:
        type: string
        nullable: true
      extra_address_state:
        type: string
        nullable: true
      extra_address_zip:
        type: string
        nullable: true
      pack_scheduled_date:
        type: string
        format: date
        example: 2018-03-08
        nullable: true
      pickup_scheduled_date:
        type: string
        format: date
        example: 2018-03-09
        nullable: true
      delivery_scheduled_date:
        type: string
        format: date
        example: 2018-03-10
        nullable: true
      remarks:
        type: string
        example: please be careful with my stuff
        nullable: true
      other_move_from:
        type: string
        nullable: true
      other_move_to:
        type: string
        nullable: true
      other_move_net_pounds:
        type: number
        format: double
        example: 4.50
        nullable: true
      other_move_progear_pounds:
        type: number
        format: float
        example: 99.09
        nullable: true
      service_member_signature:
        type: string
        example: Focaccia Roll
        nullable: true
      date_signed:
        type: string
        format: date
        example: 2018-01-23
        nullable: true
      contractor_address_number:
        type: string
        nullable: true
      contractor_address_street:
        type: string
        nullable: true
      contractor_address_city:
        type: string
        nullable: true
      contractor_address_state:
        type: string
        nullable: true
      contractor_address_zip:
        type: string
        nullable: true
      contractor_name:
        type: string
        example: Mayflower Transit
        nullable: true
      nonavailability_of_signature_reason:
        type: string
        example: service member not present
        nullable: true
      certified_by_signature:
        type: string
        example: Sally Crumpet
        nullable: true
      title:
        type: string
        example: Colonel Crumpet
        nullable: true
  IndexForm1299Response:
    type: array
    items:
      $ref: '#/definitions/Form1299Response'
  Form1299Response:
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      form_completed:
        type: boolean
        example: false
      other_params: # TODO ADD all the params to return in the response
    required:
    - id
    - created_at
    - updated_at
    - form_completed
