swagger: '2.0'
info:
  description: The API for my.move.mil
  version: 0.0.1
  title: my.move.mil
  contact:
    email: ppp@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

basePath: /api/v1

paths:
  /issues:
    post:
      summary: Create a new issue
      description: Issues represent problems or suggestions for the app, this creates a new one.
      operationId: createIssue
      tags:
        - issues
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: createIssuePayload
        required: true
        schema:
          type: object
          required:
            - description
          properties:
            description:
              type: string
              example: This is a test issue
      responses:
        201:
          description: created issue
          schema:
            $ref: '#/definitions/Issue'
        400:
          description: invalid request
    get:
      summary: List all issues
      description: List all issues
      operationId: indexIssues
      tags:
        - issues
      produces:
      - application/json
      responses:
        200:
          description: list of issues
          schema:
            type: array
            items:
              $ref: '#/definitions/Issue'
        400:
          description: invalid request

definitions:
  Issue:
    type: object
    required:
    - id
    - description
    - created_at
    - updated_at
    properties:
      id:
        type: string
        format: uuid
        example: c56a4180-65aa-42ec-a945-5fd21dec0538
      description:
        type: string
        example: This is a test issue
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
