swagger: '2.0'
info:
  description: The API for my.move.mil
  version: 0.0.1
  title: my.move.mil
  contact:
    email: ppp@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

basePath: /api/v1

paths:
  /issues:
    post:
      summary: Create a new issue
      description: Issues represent problems or suggestions for the app, this creates a new one.
      operationId: createIssue
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: issue
        schema:
          type: object
          required:
          - issue
          properties:
            issue:
              type: string
              example: This is a test issue
      responses:
        201:
          description: created issue
          schema:
            $ref: '#/definitions/Issue'
        400:
          description: invalid request
    get:
      summary: List all issues
      description: List all issues
      operationId: indexIssues
      produces:
      - application/json
      responses:
        200:
          description: list of issues
          schema:
            type: array
            items:
              $ref: '#/definitions/Issue'
        400:
          description: invalid request

definitions:
  Issue:
    type: object
    required:
    - id
    - issue
    properties:
      id:
        type: string
        example: 1
      issue:
        type: string
        example: This is a test issue
