swagger: '2.0'
info:
  description: The public API for my.move.mil
  version: 0.0.1
  title: my.move.mil
  contact:
    email: ppp@truss.works
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /tsp:
    $ref: 'tsp/paths.yaml#/Tsps'
  /tsp/{tspUuid}/shipments:
    $ref: 'tsp/paths.yaml#/TspShipments'
