development:
  dialect: "postgres"
  database: "dev_db"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "mysecretpassword"

test:
  dialect: "postgres"
  database: "test_db"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "mysecretpassword"

container:
  dialect: "postgres"
  database: "app"
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASSWORD" }}
  options:
    sslmode: "require"
