dev:
  dialect: "postgres"
  database: "dev_db"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "mysecretpassword"

test:
  dialect: "postgres"
  database: "test_db"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "mysecretpassword"
